version: '3'
services:
  node-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:9090"
    volumes:
      - ./:/usr/src/app

  client:
    build:
      context: .
    ports:
      - "4040:4040"

  mongo:
    image: mongo:3.6

